package com.hxh_environment.api.domain.enums;

public enum ClassName {
  ILLUSIONIST, CIRCUS,
  MOBSTER, MILITARY, TERRORIST,
  SWORDSMAN, SAMURAI,
  NINJA, THIEF,
  NETRUNNER, EXPERIMENT,
  SCIENTIST,
  PALADIN, MONK,
  COLLECTOR,
  GENIUS,
  MAGIC_WEAPON, MAGIC_TAMER, MAGIC_BEAST,
  HUNTER,
  TRIBAL, KURUTA;
}
